CREATE TABLE IF NOT EXISTS db_migration (
   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   num INTEGER NOT NULL,
   migration_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
   filename VARCHAR(100) NOT NULL
);
